function [dia,mes,ano,hora,latitud,longitud,direccion,opciones_avanzadas]=inputdialog(dir)

hfig=figure('CloseRequestFcn',@close_req_fun,'menu','none');

x0=250;
y0=350;
width=800;
height=600;

    try
        %create GUI
        set(hfig,'menu','none','position',[x0,y0,width,height])
        
        text_title=uicontrol('Style', 'text', 'String', 'Busqueda SAR','FontSize',18, ...
            'Parent',hfig,'Units','Normalized', ...
            'Position', [.1, .85, .8, .08]);
        text_subtitle=uicontrol('Style', 'text', 'String', 'Aplicación de asistencia a la búsqueda en casos SAR marítimos.','FontSize',14,...
            'Parent',hfig,'Units','Normalized', ...
            'Position', [.1, .78, .8, .08]);
        text_asking=uicontrol('Style', 'text', 'String', 'Ingrese los siguientes datos del evento SAR','FontSize',11,...
            'Parent',hfig,'Units','Normalized', ...
            'Position', [.1, .64, .8, .08]);
        text1=uicontrol('Style', 'text', 'String', 'Dia[dd]', ...
            'Parent',hfig,'Units','Normalized', ...
            'Position', [.15, .57, .1, .08]);
        field1=uicontrol('Style', 'Edit', 'String', 'dd', ...
            'Parent',hfig,'Units','Normalized', ...
            'Position', [.15, .57, .10, .04]);
        text2=uicontrol('Style', 'text', 'String', 'Mes[mm]', ...
            'Parent',hfig,'Units','Normalized', ...
            'Position', [.35, .57, .1, .08]);
        field2=uicontrol('Style', 'Edit', 'String', 'mm', ...
            'Parent',hfig,'Units','Normalized', ...
            'Position', [.35, .57, .1, .04]);
        text3=uicontrol('Style', 'text', 'String', 'Año[aaaa]', ...
            'Parent',hfig,'Units','Normalized', ...
            'Position', [.55, .57, .1, .08]);
        field3=uicontrol('Style', 'Edit', 'String', 'aaaa', ...
            'Parent',hfig,'Units','Normalized', ...
            'Position', [.55, .57, .1, .04]);
        text4=uicontrol('Style', 'text', 'String', 'Hora[HH:MM]', ...
            'Parent',hfig,'Units','Normalized', ...
            'Position', [.725, .57, .15, .08]);
        field4=uicontrol('Style', 'Edit', 'String', 'HH:MM', ...
            'Parent',hfig,'Units','Normalized', ...
            'Position', [.75, .57, .1, .04]);      
        text5=uicontrol('Style', 'text', 'String','Latitud [-90°/90°]', ...
            'Parent',hfig,'Units','Normalized', ...
            'Position', [.2, .44, .2, .08]);
        field5=uicontrol('Style', 'Edit', 'String', ' ', ...
            'Parent',hfig,'Units','Normalized', ...
            'Position', [.2, .44, .2, .04]);  
        text6=uicontrol('Style', 'text', 'String', 'Longitud [-180°/180°]', ...
            'Parent',hfig,'Units','Normalized', ...
            'Position', [.6, .44, .2, .08]);
        field6=uicontrol('Style', 'Edit', 'String', ' ', ...
            'Parent',hfig,'Units','Normalized', ...
            'Position', [.6, .44, .2, .04]);
        text7=uicontrol('Style', 'text', 'String', 'Dirección de almacenamiento de resultados', ...
            'Parent',hfig,'Units','Normalized', ...
            'Position', [.1, .31, .8, .08]);
        field7=uicontrol('Style', 'Edit', 'String', dir, ...
            'Parent',hfig,'Units','Normalized', ...
            'Position', [.1, .31, .8, .04]);        
        
        checkbox=uicontrol('Style', 'checkbox', 'String', 'Opciones avanzadas', ...
            'Parent',hfig,'Units','Normalized', ...
            'Position', [.1, .21, .8, .08]);

        uicontrol('Style', 'pushbutton', 'String', 'OK', ...
            'Parent',hfig,'Units','Normalized', ...
            'Position', [.42 .1 .15 .1],...
            'Callback','close(gcbf)');
%         cancel=uicontrol('Style', 'pushbutton', 'String', 'cancel', ...
%             'Parent',hfig,'Units','Normalized', ...
%             'Position', [.55 .1 .05 .05],...
%             'Tag','0','Callback',@cancelfun);

        %wait for figure being closed (with OK button or window close)
        uiwait(hfig)
        %figure is now closing

        dia=field1.String;
        mes=field2.String;
        ano=field3.String;
        hora=field4.String;
        latitud=field5.String;
        longitud=field6.String;
        direccion=field7.String;

        opciones_avanzadas=checkbox.Value;


        %actually close the figure
        delete(hfig)

    catch
        delete(hfig)
    end
end
function cancelfun(h,~)
set(h,'Tag','1')
uiresume
end
function close_req_fun(~,~)
uiresume
end